name: CI
on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "30 5 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: sterlingwes/firedanger/.github/actions/yarn-install@main

      - name: Pull latest FDR file
        run: yarn fetch-fdr

      - name: Pull districts
        run: ./scripts/download-districts.sh
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn push
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Notify
        run: yarn workspace site specific
        env:
          GMAIL: ${{ secrets.GMAIL }}
          GMAIL_U: ${{ secrets.GMAIL_U }}
          GMAIL_R: ${{ secrets.GMAIL_R }}
