name: CI
on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 5 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: sterlingwes/firedanger/.github/actions/yarn-install@main

      - name: Pull latest FDR file
        run: yarn fetch-fdr

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn push
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
